#!c:\users\marti\onedrive - hanzehogeschool groningen\school\portfolio\firewall_configuration_tool\configuratie_visualisatie_firewalls_webapp\env\scripts\python.exe

import sys
import pdfcrowd

args = []

if len(sys.argv) == 1 or sys.argv[1] == 'help':
    args.append('help')

args.append('html2pdf')

try:
    pdfcrowd.main(args + sys.argv[1:], converter_known = True)
except pdfcrowd.Error as why:
    sys.stderr.write('Pdfcrowd Error: {}\n'.format(why))
    sys.exit(1)
